language: cpp
sudo: required
compiler:
    - gcc
    # Change this to your needs
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-8.3; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-8.3" CC="gcc-8.3"; fi
    - sudo apt-get install gcc-multilib
script: cd cmake && cmake ./ && make
